Skip processing in some sets
4dn-dcic/foursight pull request #409
Opened 2021-03-01 16:35 UTC by Lmercadom

2021-03-09 16:53 UTC, aschroed requested changes

2021-03-10 22:17 UTC, Lmercadom commented on chalicelib/checks/wfr_checks.py
> +                    org = re['biosample']['biosource'][0]['individual']['organism']['name']
I added organism != No value in the search query

2021-03-10 22:18 UTC, Lmercadom commented on chalicelib/checks/helpers/wfr_utils.py
>              assert len(organisms) == 1
I added a special case for multiple organisms

2021-03-11 14:05 UTC, aschroed approved these changes

2021-03-11 15:08 UTC, merged